name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.x'

            - name: Install dependencies
              run: |
                go mod tidy
                go install github.com/becheran/go-testreport@latest

            - name: Build
              run: go build -v ./...

            - name: Run tests
              run: go test -json ./test > test-results.json

            - name: Report
              uses: becheran/go-testreport@main
              with:
                input: test-results.json